### PR TITLE
feat(agents): Mistral Vibe pre_tool arg-rewrite hook

### PR DESCRIPTION
**Pull request by lwandrebeck**
Add a pre_tool hook that transparently reroutes Vibe's native bash through the lean-ctx compression CLI (cat/head/tail -> lean-ctx read, grep -> lean-ctx grep, else lean-ctx -c '...'), mirroring the Codex PreToolUse pattern. read_file/grep are steered onto ctx_read/ctx_search in Replace mode; write tools always pass through.

- hook_handlers/vibe.rs: handler + pure, testable decide() core
- cli dispatch: 'hook vibe-pre-tool' subcommand (watchdog-exempt)
- hooks/agents/vibe.rs: install MCP via registry writer (fixes config overwrite bug) + idempotent ~/.vibe/hooks.toml writer
- hooks/tests.rs: serialize env-mutating mode tests via test_env_lock to fix a latent parallelism race

Verified end-to-end through Vibe's own HookExecutor + HookConfig.

## Summary

Enhance Mistral Vibe support

## Test plan

- [X] `cd rust && cargo test`
- [X] `cd rust && cargo clippy --all-targets --all-features -- -D warnings`
- [X] `cd rust && cargo fmt --check`
- [ ] If cookbook/packages changed: relevant `npm test` / build steps

## Notes for reviewers

- Risk areas / edge cases:
- Backwards compatibility: Mistral Vibe 2.21.0 necessary
- Docs updated (links/files):

## Contributor License Agreement

First-time contributors: a bot will ask you to sign our one-time
[CLA](https://github.com/yvgude/lean-ctx/blob/main/CLA.md) (it keeps lean-ctx
Apache-2.0 and free for individual developers — see §8). You sign **once** by
replying to this PR with: `I have read the CLA Document and I hereby sign the CLA`

### CODE REVIEW

**Review by yvgude — APPROVED** [review]
## Code Review: feat(agents): Mistral Vibe pre_tool arg-rewrite hook

Well-structured feature that mirrors the existing Codex PreToolUse pattern.

**What it does:**
- `hook_handlers/vibe.rs`: Handler with a pure, testable `decide()` core that routes Vibe bash commands through lean-ctx compression
- `hooks/agents/vibe.rs`: MCP registration via registry writer (fixes config overwrite bug) + idempotent `~/.vibe/hooks.toml` writer
- `cli dispatch`: Adds `hook vibe-pre-tool` subcommand (watchdog-exempt)
- Fixes a latent parallelism race in hook tests via `test_env_lock`

**Dependency:** Uses `crate::core::runtime_flags` which is introduced in PR #1102. This PR should be merged AFTER #1102 to avoid compilation errors.

**Merge order:** #1102 (runtime_flags + dispatch extraction) → #1096 (Vibe hook) → rebase both on `main` first.

LGTM — merge after #1102.

**Comment by yvgude** [comment]
Merged to main via CLI rebase+merge.
